#!/usr/bin/env ruby

while gets
    l = $_.chomp
    if l == "Afghanistan (Interim Authority)"
        puts "Afghanistan"
    elsif l == "U.S.S.R."
        puts "Russia"
    elsif l == "Bosnia" || l == "Bosnia-Herzegovina" || l == "Bosnian Federation"
        puts "Bosnia and Herzegovina"
    elsif l == "Brunei Darussalam"
        puts "Brunei"
    elsif l == "Byelorussia"
        puts "Belarus"
    elsif l == "Congo" || l == "Democratic Republic of Congo" || l == "Zaire"
        puts "Democratic Republic of the Congo"
    elsif l == "Czechoslovakia"
        puts "Czech Republic"
    elsif l == "Dahomey (Benin)"
        puts "Benin"
    elsif l == "East Timor"
        puts "Indonesia"
    elsif l == "Federal Republic of Germany" || l == "German Democratic Republic"
        puts "Germany"
    elsif l == "Former Yugoslav Republic of Macedonia"
        puts "Macedonia"
    elsif l == "Ivory Coast"
        puts "Cote d'Ivoire"
    elsif l == "Khmer Republic (Cambodia)"
        puts "Cambodia"
    elsif l == "Kirghizia"
        puts "Kyrgyzstan"
    elsif l == "Korea" || l == "Republic of Korea"
        puts "South Korea"
    elsif l == "Kosovo" || l == "Serbia and Montenegro" || l == "Serbia-Montenegro (Kosovo)" || l == "Yugoslavia" || l == "Yugoslavia (Kosovo)"
        puts "Serbia"
    elsif l == "Palestinian Authority"
        puts "Palestine"
    elsif l == "People's Republic of China" || l == "People’s Republic of China"
        puts "China"
    elsif l == "Slovak Republic"
        puts "Slovakia"
    elsif l == "Southern Rhodesia (Zimbabwe)" || l == "Zimbabwe Rhodesia"
        puts "Zimbabwe"
    elsif l == "St. Christopher and Nevis" || l == "St. Kitts and Nevis"
        puts "Saint Kitts and Nevis"
    elsif l == "St. Lucia"
        puts "Saint Lucia"
    elsif l == "St. Vincent and the Grenadines"
        puts "Saint Vincent and the Grenadines"
    elsif l == "The Gambia"
        puts "Gambia"
    elsif l == "Upper Volta"
        puts "Burkina Faso"
    elsif l == "Vatican City"
        puts "Holy See (Vatican City)"
    elsif l == "Western Samoa"
        puts "Samoa"
    else
        puts l
    end
end
